# Generated by Django 4.1.7 on 2025-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('physical', 'Physical Asset'), ('digital', 'Digital Asset')], max_length=20)),
                ('asset_type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner_wallet', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/')),
            ],
        ),
    ]
