# Generated by Django 4.1.7 on 2025-10-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_asset_owner_contact_asset_owner_name_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='owner_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
